name: 葱花视频

on:
  workflow_dispatch:

  schedule:
     - cron: '*/30 * * * *'
  watch:
    types: started
jobs:
  build:
    env:
      TASKCENTERBODY: ${{ secrets.TASKCENTERBODY }}
      SHAREBODY: ${{ secrets.SHAREBODY }}
      SHAREREWARDBODY: ${{ secrets.SHAREREWARDBODY }}
      TIMEREDBODY: ${{ secrets.TIMEREDBODY }}
      READBODY: ${{ secrets.READBODY}}
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【葱花视频】'
        if: env.TASKCENTERBODY
        if: env.READBODY
        if: env.SHAREBODY
        
        run: |
          node Task/RONGHUA_VIDEO.js
        env:
          TASKCENTERBODY: ${{ secrets.TASKCENTERBODY }}
          SHAREBODY: ${{ secrets.SHAREBODY }}
          SHAREREWARDBODY: ${{ secrets.SHAREREWARDBODY }}
          TIMEREDBODY: ${{ secrets.TIMEREDBODY }}
          READBODY: ${{ secrets.READBODY}}
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
